import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'about-agility',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics'],
    },
    {
      type: 'category',
      label: 'Analyze PCAP files',
      items: ['Analyze PCAP files/start-a-new-analysis'],
    },
  ],
  api: [
    
    'hello',
    {
      type: 'autogenerated',
      dirName: 'api-webhooks',  
    }
  ],
  install: [
    
    'hello',
    {
      type: 'autogenerated',
      dirName: 'installation-reference',  
    }
  ],
  
};

export default sidebars;
